#!/usr/bin/env python
import os, glob
from os.path import join, exists
from fabricate import main, autoclean, run

BUILD = 'build'

def build():
    compile('seq')

def compile(base):
    run('python',base+'.py', join(BUILD,base))

def clean():
    autoclean()

main()
