#!/usr/bin/env python
import glob
from fabricate import main, autoclean, run

BOARD = 'icestick'

#tests = glob.glob('*.py')
#tests = ['out.py']
#tests = ['inout.py']
#tests = ['mov.py']
#tests = ['and.py']
#tests = ['or.py']
#tests = ['xor.py']
#tests = ['add.py']
#tests = ['sub.py']
#tests = ['count.py']
#tests = ['jmp.py']
#tests = ['alu.py']
tests = ['blink.py']

def build():
    for test in tests:
        if test in ['setup.py']: continue
        if test.startswith('_'): continue

        base, suffix = test.split('.')
        compile(base)

def compile(base):
    run('magma','-b',BOARD,base)

def clean():
    autoclean()

main()
